version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      javascript-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/ingestion
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
